- helm/templates/deployment-router.yaml
Fixes #6 
This adds the missing `--k8s-namespace` arg to the router chart, which is required for the router to watch the namespace it was installed in. If unset, the router will try to watch the `default` namespace only.
> :bug: add namespace to router chart

- .github/workflows/helm-lint.yml
- .github/workflows/helm-release.yml
This PR adds Github Actions workflows that can run `helm lint` on the Helm charts, and release Helm charts to Github using Github Pages as a publishing source. 
**Action Required - Set Up `gh-pages` Branch** 
Before the Helm release workflow will work correctly, there is setup required by a maintainer. The steps can be found in the [Helm docs](https://helm.sh/docs/topics/chart_repository/#github-pages-example), and should only take about 5 minutes. 
A successful test run of this workflow can be seen in my fork here: https://github.com/0xThresh/vllm-production-stack/actions/runs/12979140685/job/36194506180 
And you can see the charts that I successfully published on my repo here: https://0xthresh.github.io/vllm-production-stack/index.yaml
While I hope this is a helpful PR, I also …
> feat: Add Github workflows to lint and release Helm chart

- .gitignore
- helm/Chart.yaml
- helm/templates/deployment-vllm-multi.yaml
- helm/templates/secrets.yaml
- helm/values.schema.json
- helm/values.yaml
- tutorials/02-basic-vllm-config.md
- tutorials/03-load-model-from-pv.md
- tutorials/04-launch-multiple-model.md
- tutorials/05-offload-kv-cache.md
- tutorials/assets/values-02-basic-config.yaml
- tutorials/assets/values-03-match-pv.yaml
- tutorials/assets/values-04-multiple-models.yaml
- tutorials/assets/values-05-cpu-offloading.yaml
This PR fixes #14 
Now the deployment uses the secret in the helm chart to hold the hugging face token, which can be safely referenced in the deployment.
> feat: Use secrets to configure HF_TOKEN

- tutorials/01-minimal-helm-installation.md
- Change name from llmstack to vllm
- Fix explanation for `sudo kubectl get pods`, not only it needs to show "Running", but also it needs to be "Ready"
> [Doc] Fix Readme for 01 example

- tutorials/00-install-kubernetes-env.md
This PR includes some troubleshooting tips to fight against the common seen "too many open files" issue, when installing workloads in minikube.
Hopefully it can (1) make the tutorial more robust, (2) save people some time during the setup.
> Polish the 'Setting Up a Kubernetes Environment with GPUs' tutorial

- helm/templates/ingress.yaml
- helm/values.yaml
Adds an ingress configuration to the routerSpec, enabling connections to the router service from outside the cluster. 
Closes https://github.com/vllm-project/production-stack/issues/28
> feat: Add ingress configuration to routerSpec

- helm/values.yaml
https://github.com/vllm-project/production-stack/pull/22 updated the schema to use `hf_token` instead of an environment variable config in `Values.yaml`, but the commented out example in the values file was not updated to reflect this. This PR corrects the example to use the new hf_token value.
> fix: Update Helm values example to use new hf_token value

- examples/batch.jsonl
- examples/batch.py
- setup.py
- src/vllm_router/files/__init__.py
- src/vllm_router/files/file_storage.py
- src/vllm_router/files/files.py
- src/vllm_router/files/storage.py
- src/vllm_router/router.py
This is the part 1 of #47 
file.Storage has been introduced to abstract file operations, to support both OpenAI files and the uploads API. The user-id in the interface is defaulted to uid-default, which is kept for future extensibility.
I believe OpenAI uses a database, such as PostgreSQL, to store file metadata. For now, we are using simple file operations to handle this.
I’ve raised this PR to discuss whether this approach aligns with our requirements. Then will implement the batch API in part 2.
> feat: OpenAI batch API part 1

- src/examples/example_file_upload.py
- src/vllm_router/router.py
This PR fixes a problem that the router will break when the "purpose" does not exist in the query to `/files` endpoint.
It also contains a minimal example to query the `/files` endpoint.
> [Add] fix for router files api and example to post query to the api

- requirements-test.txt
- src/tests/test_file_storage.py
> chore: Add test cases for file storage

- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
Fix #91
Fix #92
Please check "PR Title and Classification" section.
> [Doc] Add PR template

- .github/workflows/router-docker-release.yml
- .github/workflows/router-e2e-test.yml
- src/tests/requirements.txt
- src/vllm_router/perf-test.sh
- utils/install-minikube-cluster.sh
- Add router-e2e-test workflow for PR validation with performance tests
- Add router-docker-release workflow for automated image builds
FIX #74 
---
<details>
<ul>
<li><code>[Bugfix]</code> …
> [CI/Build] : add GitHub Actions workflows for router (#74)

- helm/Chart.yaml
- helm/templates/deployment-vllm-multi.yaml
- helm/values.yaml
This PR introduces support for tensor parallelism in vLLM engines by modifying the Helm chart template to include shared memory configuration when tensorParallelSize is set. This enables multi-GPU execution with tensor parallelism degree of more than one. 
FIX #95 
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is …
> Enable multi-GPU inference in vLLM with tensor parallelism

- tutorials/05-offload-kv-cache.md
Fixed chart name `vllm/production-stack` -> `vllm/vllm-stack` in tutorial 05.
> [Doc] minor tutorial doc fix

- tutorials/02-basic-vllm-config.md
- tutorials/03-load-model-from-pv.md
- tutorials/04-launch-multiple-model.md
- tutorials/05-offload-kv-cache.md
Aligned tutorial docs with chart:
- Changed instances of `production-stack` to `vllm-stack` (chart-name)
- Changed instances of `llmstack` to `vllm` (release-name)
> [Doc] fixed chart-name related misalignments in tutorial docs

- src/vllm_router/httpx_client.py
- src/vllm_router/router.py
- src/vllm_router/utils.py
httpx client has a default max_connections(100) which will block the requests if the concurrency is over 100.
This commit enhances the router's concurrency capabilities. Key changes:
1. Set `httpx.AsyncClient` max connections to unlimited to unblock the requests.
2. In `process_request`, overwrite host header for proxies routing by host.
3. Call `set_ulimit` in `main` to prevent uvicorn from dropping requests due to high FD count.
> Fix the problem of 1k prompts.

- observability/README.md
- observability/install.sh
- observability/vllm-dashboard.json
- src/tests/perftest/request_generator.py
- src/tests/requirements.txt
- src/vllm_router/engine_stats.py
- src/vllm_router/request_stats.py
- src/vllm_router/requirements.txt
- src/vllm_router/router.py
- src/vllm_router/run-router.sh
- utils/install-minikube-cluster.sh
Feature Router observability (Current QPS, router-side queueing delay, etc) Part 1: #78 
Due to the complexity and large task, I will split this feature into 2 sub-small PR for easier manage:
- First one will be the setup visualization, update router for localhost logging, etc.
- Second will be connect the Router with Prometheus and visualize the output on Grafana
This PR is to create 4 main things for the first part of the Router Observability update:
- Update vLLM Dashboard Grafana to align with the reference from @YuhanLiu11 combine with add-on. The metrics include
- __Overview of the system__: 
- Available vLLM instances
- Request latency distribution
- Number of currently healthy vLLM pods
- Average latency
- __QoS Information__:
- Current QPS
- Request TTFT distribution
- …
> Feat: Router observability (Current QPS, router-side queueing delay, etc) Part 1

- src/tests/test_singleton.py
- src/vllm_router/engine_stats.py
- src/vllm_router/request_stats.py
- src/vllm_router/router.py
- src/vllm_router/routing_logic.py
Enhance Singleton Design Pattern for EngineStat Scraper, RequestStat Monitor, and Router as mentioned in #86 
---
<details>
<ul>
<li><code>[Bugfix]</code> …
> [Misc] Implement Singleton Design Pattern for EngineStat Scraper, RequestStat Monitor, and Router

- .github/workflows/functionality-helm-chart.yml
- .gitignore
- docker/Dockerfile
- pyproject.toml
- setup.py
- src/vllm_router/router.py
- src/vllm_router/version.py
FIX #87 
```
vllm-router --version
vllm-router 0.0.9.dev2+g89305e3.d20250219
```
> [router] setuptools_scm to support version argument

- helm/templates/deployment-vllm-multi.yaml
- tutorials/09-lora-enabled-installation.md
- tutorials/assets/values-07-lora-enabled.yaml
Progress toward  [#205](https://github.com/vllm-project/production-stack/issues/205)
<details>
This PR just add some manually LoRA enablement tutorial, `tutorials/assets/values-07-lora-enabled.yaml` and simple deployment yaml template update to have an `enableLoRA: true` configuration for the helm chart.
`tutorials/09-lora-enabled-installation.md` describes how to manually add an adapter to an vllm deployment in production stack.
<ul>
<li><code>[Feat]</code> LoRA enablement support.</li>
<li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>
> Manually Enable LoRA Adapters using existing Router and vLLM deployment

- .github/curl-05-secure-vllm.sh
- .github/values-05-secure-vllm.yaml
- .github/workflows/functionality-helm-chart.yml
- helm/templates/deployment-router.yaml
- helm/templates/deployment-vllm-multi.yaml
- helm/templates/secrets.yaml
- helm/values.schema.json
- helm/values.yaml
- src/vllm_router/service_discovery.py
- tutorials/11-secure-vllm-serve.md
- tutorials/assets/values-11-secure-vllm.yaml
FIX https://github.com/vllm-project/production-stack/issues/150
---
<details>
<ul> …
> [Feat] add vllm-api-key

- src/vllm_router/app.py
- src/vllm_router/parsers/parser.py
- src/vllm_router/services/request_service/request.py
- src/vllm_router/services/request_service/rewriter.py
This PR provides a new module called `RequestRewriter`, which can take in the request body and rewrite the request before it's routed to the endpoint.
This is to support more flexible use cases in the future, such as the "personal identifiable information" (PII) detection.
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the type of change. Please use one of the …
> [Feat] Request rewriter interface in router

- .github/workflows/router-e2e-test.yml
The e2e test uses python 3.10. The setup.py script requires 3.12. There is an e2e test failure [here](https://github.com/vllm-project/production-stack/actions/runs/13865700515/job/38804225593?pr=235). This PR is to reconcile the differences.
@Shaoting-Feng @YuhanLiu11 @ApostaC
> chore: update e2e test to use python 3.12 to match setup.py requirements

- src/vllm_router/experimental/README.md
- src/vllm_router/experimental/feature_gates.py
- src/vllm_router/experimental/pii/__init__.py
- src/vllm_router/experimental/pii/analyzers/__init__.py
- src/vllm_router/experimental/pii/analyzers/base.py
- src/vllm_router/experimental/pii/analyzers/factory.py
- src/vllm_router/experimental/pii/analyzers/presidio.py
- src/vllm_router/experimental/pii/analyzers/regex.py
- src/vllm_router/experimental/pii/config.py
- src/vllm_router/experimental/pii/middleware.py
- src/vllm_router/experimental/pii/requirements.txt
- src/vllm_router/experimental/pii/test_pii.sh
- src/vllm_router/experimental/pii/types.py
FIX #227
This is an initial draft for PII detection. This PR only includes the NLP updates in feature gates. The full router integration can be found [here](https://github.com/vllm-project/production-stack/compare/main...rootfs:pii-detect?expand=1).
At the moment, only PII detection is enabled. I also want to have PII redaction, but it requires router support to rewrite HTTP header. 
The demo can be found:
[![asciicast](https://asciinema.org/a/708119.svg)](https://asciinema.org/a/708119)
cc @ApostaC @YuhanLiu11 @Shaoting-Feng
> feat: support PII detection in http request

- helm/templates/service-vllm.yaml
Addresses #312
<h3>Enables multiple Kubernetes services when multiple models are specified in modelSpec</h3>
<p>Iterates over the <code>modelSpec</code> specifications and changes <code>.</code> to <code>$</code> to grab port info from the parent scope.</p>
> [Feat] Multiple service creation when multiple models specified

- helm/templates/deployment-cache-server.yaml
- helm/templates/deployment-router.yaml
- helm/values.yaml
Add nodeSelectorTerms to router and cache servers to select on which nodes these deployments should be put on. Right now only the "model"/GPU deployment has this possibility.
---
> [Feat] Add nodeSelectorTerms for router & cacher servers

- docs/source/user_manual/router/cmd.rst
- src/vllm_router/app.py
- src/vllm_router/parsers/parser.py
- src/vllm_router/routers/main_router.py
- src/vllm_router/services/callbacks_service/callbacks.py
- src/vllm_router/services/callbacks_service/custom_callbacks.py
- src/vllm_router/services/request_service/request.py
This PR adds a way to call custom callbacks at two points in the code base, allowing the router to be used in places where custom business logic is required. The implementation is inspired by [litellm's callback system](https://fastapi.tiangolo.com/tutorial/background-tasks/).
The first point is right after a request comes in, where you can validate the request and return a response overwrite, which will return that response to the user and end the request. This can be used for api-key validation.
The second point is after a request has finished completely. This is achieved using [background tasks](https://fastapi.tiangolo.com/tutorial/background-tasks/), so it's non-blocking and can be used for logging.
More locations and callbacks can of course be added later, I suggest starting with …
> [Router] Add custom callbacks service

- src/vllm_router/log.py
* [logging.StreamHandler](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler) emits the log as stderr by default.
* It will be the issue at the production logging system where stderr as the system error.
* In our production, the logging detect system recognizes it as the error status since it emits stderr even if the log level is info.
* To fix it properly, there should be two logging.StreamHandler. One is for stdout the other is for the stderr.
* In this change.
- logging.StreamHandler for stdout only emit until the log level is INFO.
- If the log level is greater than WARN, then the logger will emit the log as stderr.
* And the other fix is propagate, if the propagate is set as True, in real logging system, it detects duplicated log from unicorn. So to prevent …
> [Bugfix] Update logger handler to handle stdout/stderr prorperly

- src/vllm_router/app.py
log_stats should receive app and interval but only pass the interval parm when creating the thread, so I fix to pass them properly.
https://github.com/vllm-project/production-stack/blob/2402e6b580b3bcc0951c26d2575039c6cf3b0e9a/src/vllm_router/stats/log_stats.py#L21
FIX #335 
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The …
> [Bugfix] Fix thread creation to pass parameters properly.

- tutorials/12-distributed-tracing.md
- tutorials/assets/otel-example/jaeger-collector.yaml
- tutorials/assets/otel-example/jaeger-query.yaml
- tutorials/assets/otel-example/jaeger.yaml
- tutorials/assets/otel-example/otel-collector-config.yaml
- tutorials/assets/otel-example/otel-collector.yaml
Addresses #77
<h3>Added OpenTelemetry Collector Example w/ Jaeger UI</h3>
<p>This PR adds the following files to a <code>otel-example</code> folder under <code>helm</code>: </p>
<ul>
<li><code>jaeger.yaml</code> configures jaeger deployment and exposes ports 4317 (gRPC) and 4318 (HTTP) for data collection.</li>
<li><code>otel-collector.yaml</code> specifies otel collection (receives trace data via OTLP), processes traces in batches, and exports to jaeger collector.</li>
<li><code>sample-otel-values.yaml</code> is the same as <code>values.yaml</code> except that we specify OTEL service name, port, and attributes to be injected into the Kubernetes manifest.</li>
</ul>
<h3>Usage</h3>
<p>First deploy jaeger, otel-collection, and the vllm model from the <code>otel-example</code> directory. …
> [Feat] OpenTelemetry Support Example

- helm/templates/deployment-vllm-multi.yaml
Added model label to deployment selector.
In order to ensure the deployments for each model select only the pods associated with their model, I added the model label to the selector.
> [Bugfix] added model name to deployment selector

- pyproject.toml
- src/vllm_router/README.md
- src/vllm_router/app.py
- src/vllm_router/parsers/parser.py
- src/vllm_router/requirements.txt
- uv.lock
We want to deploy the router part of production stack in our own environment. We make use of [Sentry](https://sentry.io) for error reporting. This PR adds the `sentry-sdk` package along with the required extras to make use of Sentry's integration with FastAPI and HTTPX. The setup will only be done in cases where the new `--sentry-dsn` flag has been set at startup. Otherwise, the router will start without any changes.
I tried my best to assume the configuration of the `pyproject.toml` and `requirements.txt` dependencies. Please let me know if I should change anything regarding the setup. Other than that, the Sentry SDK doesn't require much setup other than the call to `sentry_sdk.setup()` which monkey-patches some functions.
> [Router] add sentry sdk and cli args

- src/vllm_router/services/request_service/request.py
If the code only collects the first chunk, the full_response will be incomplete. For example:
If the JSON response is:
```json
{"key": "value", "another_key": "another_value"}
```
And it's split into two chunks:
```python
chunk1 = b'{"key": "value", "'
chunk2 = b'another_key": "another_value"}'
```
Then full_response will only contain chunk1, and the end (chunk2) is missing so then we had incomplete json responses in the callback
```python
class PostRequestCallbackHandler(CustomCallbackHandler):
async def post_request(self, request: Request, response_content: bytes) -> Any:
request_json: dict = await request.json()
if request_json.get("stream"):
return
try:
response_json = json.loads(response_content.decode("utf-8"))  # this used to crash
logger.debug(response_json)
except Exception as e: …
```
> [Router][Bugfix]: make sure to extend full_response

- src/vllm_router/dynamic_config.py
- src/vllm_router/service_discovery.py
- src/vllm_router/utils.py
Fix dynamic config
- add default value
- pass *app* parameter
FIX #596   (*link existing issues this PR will resolve*)
---
<details>
<ul> …
> [Bugfix] fix dynamic config

- src/vllm_router/app.py
- src/vllm_router/parsers/parser.py
- src/vllm_router/service_discovery.py
allow service discovery by service names
FIX #https://github.com/vllm-project/production-stack/issues/471
```bash
python3 -m  vllm_router.app --port=8000 --k8s-port=80 --service-discovery=k8s --k8s-service-discovery-type=service-name --k8s-label-selector=release=test\  --k8s-namespace=lzj --routing-logic=session --session-key=x-user-id --engine-stats-interval=10 --log-stats 
/root/code/production-stack/src/vllm_router/parsers/parser.py:20: RuntimeWarning: Failed to read commit hash:
No module named 'vllm_router._version'
from vllm_router.version import __version__
[2025-07-18 02:15:20,301] INFO: Scraping metrics from 0 serving engine(s) (engine_stats.py:146:vllm_router.stats.engine_stats)
[2025-07-18 02:15:20,302] INFO: Initializing session-based routing logic with kwargs: {'session_key': …
```
> [Feat] allow service discovery by service names

- src/vllm_router/app.py
- src/vllm_router/parsers/parser.py
- src/vllm_router/service_discovery.py
> [Feat][Router] Add configurable timeout_seconds for Kubernetes watchers

- deployment_on_cloud/gcp/clean_up_basic.sh
- deployment_on_cloud/gcp/entry_point_basic.sh
- tutorials/assets/gke-example/values-01-offload-kv-cache-local-disk.yaml
- tutorials/cloud_deployments/02-GCP-GKE-deployment.md
- tutorials/cloud_deployments/04-GCP-GKE-lmcache-local-disk.md
Add GKE example for lmcache offloading with cpu ram and local disk offloading both enabled. In this example we use local SSD as the local disk through Kubernetes ephemeral storage(emptyDir)
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the …
> [Feat] Add GKE example for lmcache cpu ram + local disk offloading

- helm/templates/deployment-vllm-multi.yaml
- pyproject.toml
- src/vllm_router/routers/routing_logic.py
- tutorials/assets/values-17-kv-aware.yaml
[Feat] Use the lmcache 0.3.5 for kvaware routing
- Upgrade lmcache to 0.3.5
- Modify lmcache call parameters
- Fix Env
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the type of change. Please use one of the …
> [Feat] Use the lmcache 0.3.5 for kvaware routing

- observability/README.md
The observability tutorial has a few outdated command. This PR fix it. 
---
<details>
<ul> …
> [bugfix] Small fix to observability tutorial

- pyproject.toml
- src/vllm_router/requirements.txt
…equirements.txt
FIX https://github.com/vllm-project/production-stack/issues/714
---
<details>
<ul> …
> [Bugfix] Update aiohttp to resolve CVE-2024-23334 vulnerability
