vllm-project/production-stack

src/router/requirements.txt, src/router/routing_logic.py, src/tests/test_session_router.py
Close #8 
All the test cases pass but it is a little tricky to run the tests:
```bash
export PYTHONPATH=$(pwd)/src/router
pytest
```
it might be a good idea to turn the router into a Python package—it could make testing a lot easier and help keep things neat and tidy.
Ref #17
=> feat: Support dynamic node changes in session router

src/vllm_router/README.md
Fixed some typos and outdated stuff.
=> fix: Fix docs about router

tutorials/01-minimal-helm-installation.md, tutorials/02-basic-vllm-config.md
https://github.com/vllm-project/production-stack/issues/37
=> Fix helm chart issue

.github/workflows/functionality-helm-chart.yml
Currently, the functionality test has not been triggered when the PR is changing the helm chart.
This PR fixes this problem
=> [fix] triggers for functionality test

src/vllm_router/router.py
Avoid manual checks for two main arguments.
=> chore: Use choices in CLI

src/vllm_router/router.py
This PR is to make log stats interval configurable, it is a **hidden** argument for debug purposes. Not sure if we should make it public since it should be useless in most cases.
=> feat: Make log stats interval as a hidden CLI argument

.github/curl-01-minimal-example.sh, .github/curl-04-multiple-models.sh, .github/multiple-models.yaml, .github/port-forward.sh, .github/workflows/functionality-helm-chart.yml, tutorials/assets/example-04-openai.py
1. Add multiple model test
2. Add timeout for two jobs
=> [CI/Build] Upgrade function test

helm/templates/deployment-vllm-multi.yaml, helm/values.yaml
=> [Add] customization support for runtimeClass

src/vllm_router/router.py, src/vllm_router/routing_logic.py
The batch implementation will also use the router, so we should implement it as a simple singleton, similar to `EngineStatsScraper` and other components.
=> feat: Wrap router to a singleton

README.md
Preview: https://github.com/gaocegege/production-stack/tree/rm
=> chore: Refine README, adjust image size

src/tests/perftest/fake-openai-server.py, src/tests/perftest/request_generator.py, src/vllm_router/router.py
This PR replaces the self-incremental request_id with uuid(128bits), making the router unstateful.
Fixes: #81 
/cc @gaocegege PTAL if you have time👀
=> feat(router): generate req id with uuid.

helm/templates/deployment-router.yaml, helm/templates/ingress.yaml, helm/templates/role.yaml, helm/templates/rolebinding.yaml, helm/templates/service-router.yaml, helm/templates/serviceaccount.yaml, helm/values.yaml
Closes https://github.com/vllm-project/production-stack/issues/66. I tested this by using `helm template` with a variety of values combinations (including `enableRouter` set to true and false, along with testing the ingress `enabled` with `true` and `false` as well), and by setting a model spec locally to ensure that all the expected model resources are still built without the router.
<details>
<p>Please try to classify PRs for easy understanding of the type of …
=> Feat: Add support for disabling router

README.md, tutorials/01-minimal-helm-installation.md, tutorials/assets/values-01-2pods-minimal-example.yaml, tutorials/assets/values-02-basic-config.yaml, tutorials/assets/values-03-match-pv.yaml, tutorials/assets/values-04-multiple-models.yaml, tutorials/assets/values-05-cpu-offloading.yaml
---
<details>
<ul>
<li><code>[CI/Build]</code> for build …
=> Update yaml file for the tutorials

.github/multiple-models.yaml, .github/workflows/functionality-helm-chart.yml
This PR adds `sudo helm repo update` to the two function tests using github.actions
---
<details>
<ul> …
=> [CI/Build] Add helm update to helm func test pipeline

.github/workflows/functionality-helm-chart.yml
We should avoid using remote helm repo for func test pipeline otherwise it doesn't reflect the change to the hem chart. We now use local location `./helm`.
---
<details>
<ul> …
=> [CI/Build] Avoid using helm repo

.github/multiple-models.yaml, helm/templates/pvc.yaml, helm/values.yaml, tutorials/assets/values-01-2pods-minimal-example.yaml, tutorials/assets/values-01-minimal-example.yaml, tutorials/assets/values-02-basic-config.yaml, tutorials/assets/values-03-match-pv.yaml, tutorials/assets/values-04-multiple-models.yaml, tutorials/assets/values-05-cpu-offloading.yaml
Adds value file based accessMode Config so that the PVC policy is adjustable.
FIX #107 
---
<details>
<ul>
<li><code>[CI/Build]</code> for build …
=> [Bugfix] value file based accessMode

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, proposals/TEMPLATE.md
---
<details>
<ul>
<li><code>[CI/Build]</code> for build …
=> [Doc] Adding contributing guidelines

helm/templates/deployment-router.yaml, helm/values.yaml
Updates the Helm chart templates to support the use of `static` service discovery on the router deployment, which currently only supports `k8s` service discovery. I tested this on a local cluster using an Ollama endpoint as the static endpoint, and confirmed that I was able to curl the completions endpoint on the router and get a response to my query from the Ollama-hosted model. 
Closes https://github.com/vllm-project/production-stack/issues/104 
---
<details>
<p>Thank you for your contribution to production-stack! Before submitting the pull request, please ensure the PR meets the following criteria. This helps us maintain the code quality …
=> [Feat] Enable static service discovery on router through Helm

helm/Chart.yaml, helm/templates/_helpers.tpl, helm/templates/deployment-router.yaml, helm/templates/deployment-vllm-multi.yaml, helm/values.yaml
implements adjustable deployment strategy for both serveEngine and router. 
Also the replicaset not working for router should be fixed as well.
FIX #116  
---
<details>
<ul> …
=> feat: adjustable deployment strategy

.github/workflows/helm-release.yml
FIX #123  (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [CI/Build] Remove useless steps

observability/README.md
=> [Doc] Fix grafana graph

tutorials/02-basic-vllm-config.md
This PR adds the documentation for how to run vLLM on multiple GPUs with tensor parallelism in ``tutorials/02-basic-vllm-config.md``. 
FIX #106 
---
<details>
<ul> …
=> [Doc] Running vLLM with tensor parallelism

.github/workflows/ci.yml, setup.py, src/vllm_router/requirements.txt
Add versions in requirements.txt and setup.py
FIX #136
---
<details>
<ul> …
=> [Router] Fix unspecified versions in requirements.txt

helm/templates/pvc.yaml
This PR fixes an indentation issue in the Helm Chart’s PersistentVolumeClaim (PVC) template.
Incorrect indentation caused deployment failures or unexpected behavior in certain environments.
This fix ensures proper YAML structure and improves chart stability.
---
- [v] Make sure the code changes pass the [pre-commit](CONTRIBUTING.md) checks.
- [v] Sign-off your commit by using <code>-s</code> when doing <code>git commit</code>
- [v] Try to classify PRs for easy understanding of the type of changes, such as `[Bugfix]`, `[Feat]`, and `[CI]`.
<details>
<p>Thank you for your contribution to production-stack! …
=> [Bugfix] Fix indentation issue in Helm Chart PVC

.github/workflows/router-docker-release.yml
Ref https://github.com/vllm-project/production-stack/issues/80#issuecomment-2652913671
=> [release] Add github sha tag for router image

helm/Chart.yaml, helm/templates/deployment-vllm-multi.yaml
This PR adds vLLM v1 support to production stack. For this PR, we only enables native vLLM's v1 support as part 1. Note that currently, all the optimizations from LMCache is not supported. We will work on enabling v1 in LMCache in the coming days, and create a PR as part 2.
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The …
=> Adding vLLM v1 support (part 1)

.github/PULL_REQUEST_TEMPLATE.md
The link to CONTRIBUTING.md in the PR template was wrong (can't click and go to the right file). 
---
<details>
<ul> …
=> [Doc] Fixing CONTRIBUTING.md path issue in PR template

deployment_on_cloud/aws/set_up_efs.sh, tutorials/cloud_deployments/01-AWS-EKS-deployment.md
Remove hardcoded eks cluster name with parameter `CLUSTER_NAME`
---
<details>
<ul> …
=> [Misc] Remove hardcoded eks cluster name

community/community-event.md
This PR adds information for community meetings. 
---
<details>
<ul> …
=> [Doc] Adding community meeting info

community/community-event.md
Updates the community-event.md file so that the time only includes PT. 
---
<details>
<ul> …
=> [Doc] Updating community meeting info

.github/workflows/router-docker-release.yml
This PR fixes #163.
It's also related to #156 (as a temporary solution)
- Add a stage to sanitize the version tag.
- Also push to `lmcache/lmstack-router:latest` as it's used by the helm template as the default one.
We should stop using `lmcache/lmstack-router:latest` and move to the image in `ghcr.io` after it becomes publicly accessible. 
---
<details>
<p>Please try …
=> [Bugfix] Fix docker build problem in github workflow

.github/values-01-minimal-example.yaml, helm/Chart.yaml, helm/templates/deployment-vllm-multi.yaml, helm/templates/pvc.yaml, helm/values.yaml, tutorials/01-minimal-helm-installation.md, tutorials/assets/values-01-2pods-minimal-example.yaml, tutorials/assets/values-01-minimal-example.yaml
This PR fixes #175 
When `pvcStorage` is not provided in the values.yaml, the PVC will not be created. (Old code: will create a PVC with 20GB)
In this case, vLLM will set `HF_HOME` to `/tmp`, and anything downloaded to the local storage will be deleted when the pod is destroyed.
Also updated the tutorial in the minimal example.
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately …
=> [Feat, Misc] Disable PVC creation when `pvcStorage` is not provided

src/vllm_router/router.py
Closes #170
⚒️ with ❤️ by @siemens
---
<details>
<ul> …
=> [Feat]: add support for embeddings, rerank and score endpoints

helm/templates/deployment-vllm-multi.yaml, helm/templates/pvc.yaml, helm/templates/secrets.yaml, helm/values.schema.json, helm/values.yaml
This PR enhances the helm chart to provide more flexibility in how HuggingFace tokens are configured for model deployments. Users can now either:
1. Continue using the existing method of directly specifying tokens (which get stored in an auto-generated secret)
2. Reference existing Kubernetes secrets (useful for organizations with existing secret management)
1. Updated `values.schema.json` to support both string tokens and secret references
2. Modified `deployment-vllm-multi.yaml` to handle both token configuration methods
3. Updated `secrets.yaml` to only create secrets for directly specified tokens
4. Enhanced documentation in `values.yaml` with examples of both approaches
```yaml
modelSpec:
- name: "model1"
hf_token: "hf_xxxxxxxxxxxxx"
- name: "model2"
hf_token:
secretName: …
```
=> [Feat] Add support for external Hugging Face token secrets in Helm chart

docker/Dockerfile, setup.py
see https://github.com/vllm-project/vllm/blob/main/Dockerfile#L13
⚒️ with ❤️ by @siemens
---
<details>
<ul> …
=> [CI/Build]: bump python to 3.12 to be inline with vllm

benchmarks/multi-round-qa/plot.py, benchmarks/multi-round-qa/run.sh
Fixing minor bugs in benchmarks scripts and upload plotting scripts.
---
<details>
<ul> …
=> [Benchmark] Fixing minor bugs in benchmark scripts

src/vllm_router/request_stats.py
FIX #173 (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Router] Update qps when no requests

helm/templates/deployment-vllm-multi.yaml
An image pull secret is needed to use a vllm image from a private repository. This PR introduces a small change to the helm chart allowing specification of an image pull secret `imagePullSecret` in a `modelSpec` (where the `repository` and `tag` are specified).
---
<details>
<p>Please try to classify PRs for easy …
=> [Feat] add imagePullSecrets option to helm chart

benchmarks/multi-round-qa/run.sh, benchmarks/multi-round-qa/run_single.sh, benchmarks/multi-round-qa/warmup.sh, benchmarks/multi-round-qa/warmup_single.sh, tutorials/07-benchmark-multi-round-qa-multi-gpu.md, tutorials/07-benchmark-multi-round-qa-single-gpu.md, tutorials/07-benchmark-multi-round-qa.md, utils/install-minikube-cluster.sh
This PR adds the tutorial for reproducing multi-round QA benchmark results on 8*A100 GPUs. 
---
<details>
<ul>
<li><code>[CI/Build]</code> …
=> [Doc] Adding benchmark tutorial

helm/values.yaml
Followup to merged PR https://github.com/vllm-project/production-stack/pull/179 (issue https://github.com/vllm-project/production-stack/issues/165). This documents the change in `helm/values.yaml`. Overlooked in original PR.
FIX #165 (*link existing issues this PR will resolve*)
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. …
=> [Doc] update doc for merged PR 179

helm/templates/deployment-vllm-multi.yaml, helm/values.yaml
Per https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#chat-template: 
> In order for the language model to support chat protocol, vLLM requires the model to include a chat template in its tokenizer configuration. The chat template is a Jinja2 template that specifies how are roles, messages, and other chat-specific tokens are encoded in the input.
The default template does not work for all models. For example the `facebook/opt-125m` model requires a different template.
This PR modifies the helm chart to allow a `modelSpec` to specify a chat template. For example, for `facebook/opt-125m`:
```yaml
chatTemplate: |-
{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ 'Question:\n' + message['content'] + '\n\n' }}{% elif message['role'] == 'system' %}\n{{ …
```
=> [Feat] Allow specification of chat template

benchmarks/multi-round-qa/plot.py, benchmarks/multi-round-qa/run.sh, benchmarks/multi-round-qa/run_single.sh, tutorials/07-benchmark-multi-round-qa-single-gpu.md
Fixing some minor typos in single-GPU multi-round QA benchmark tutorial. 
---
<details>
<ul> …
=> [Doc] Minor fix in benchmark tutorial

.gitignore, helm/templates/_helpers.tpl, helm/templates/deployment-cache-server.yaml, helm/templates/deployment-vllm-multi.yaml, helm/templates/service-cache-server.yaml, tutorials/06-remote-shared-kv-cache.md, tutorials/assets/values-06-shared-storage.yaml
Add remote shared storage with LMCache.
---
<details>
<ul> …
=> [Feat] Add remote shared storage with LMCache

src/vllm_router/README.md, src/vllm_router/dynamic_config.py, src/vllm_router/engine_stats.py, src/vllm_router/router.py, src/vllm_router/routing_logic.py, src/vllm_router/service_discovery.py, src/vllm_router/utils.py
This PR creates a basic framework for configuring the router's logic during the runtime.
This provides the interface for #204 
---
<details>
<ul> …
=> [Feat] dynamic configuration support for router

README.md
The License in readme is MIT and it doesn't match with the LICENSE file. Change it to Apache 2.0.
---
<details>
<ul> …
=> [Docs] Fix the wrong license name in `README.md`

helm/Chart.yaml
Bumps the release version to 0.1.0. 
---
<details>
<ul> …
=> [Misc] Bumping vllm-stack version to 0.1.0

.github/workflows/functionality-helm-chart.yml, docker/Dockerfile, setup.py, src/vllm_router/router.py
This PR disables sementic cache in the CI tests to speed up the workflow.
---
<details>
<ul> …
=> [CI/Build][Router] Make semantic caching optional

tutorials/08-benchmark-multi-round-qa-multi-gpu.md
=> [Benchmark] Add router config in tutorial

helm/templates/deployment-vllm-multi.yaml, helm/values.schema.json, helm/values.yaml
Hi, first PR here! Just though I'd help out by adding the initContainers option to the deployment in order to allow more ways to download models/loras etc...
FIX #69
---
<details>
<ul> …
=> [Feat] Added `initContainer` to `modelSpec`

src/vllm_router/routers/main_router.py
There is one left out semantic cache related code check in the newly refactored router.
---
<details>
<ul> …
=> [Router] Fix semantic cache check in chat completion url

tutorials/08-benchmark-multi-round-qa-multi-gpu.md
Change the repository from "lmcache/*" to "vllm/*" in the section of naive k8s in tutorial 08.
---
<details>
<ul> …
=> [Doc] Change repo in tutorial 08 naive k8s

docs/README.md, docs/source/conf.py, docs/source/getting_started/examples.rst, docs/source/index.rst
* Added MWE and readme to doc content
---
<details>
<ul> …
=> [Doc] add example page and readme

tutorials/08-benchmark-multi-round-qa-multi-gpu.md
=> [Doc] Fix typo of model name and output len in AIBrix

.github/workflows/functionality-helm-chart.yml
By using `concurrency`, we can control job execution to avoid interference from other workflows.
Also, only one workflow run for the same branch (or pull request) will run at a time, and any in-progress runs will be canceled when a new one is triggered. This has been tested by my two commits.
I also added removal of outdated router image.
---
<details>
<p>Please try to …
=> [CI/Build] Add concurrency to functionality test

docs/source/_static/custom.js, docs/source/conf.py, docs/source/deployment/helm.rst, docs/source/tutorials/kv_cache.rst, docs/source/tutorials/lora_load.rst, docs/source/user_manual/kv_cache/index.rst, docs/source/user_manual/lora/manual.rst, docs/source/user_manual/router/cmd.rst, docs/source/user_manual/router/json.rst
Update tutorial docs
---
<details>
<ul>
<li><code>[Feat]</code> for new …
=> [Doc] update tutorial  and user manual docs

helm/templates/_helpers.tpl, helm/values.schema.json, helm/values.yaml
Add requestGPUType as optional to the modelSpec. 
This allows for using non standard GPU configs, like when using MIG e.g. nvidia.com/mig-4g.71gb.
The default of nvidia.com/gpu remains unchanged
FIX #252 
---
<details>
<ul> …
=> [Feat] add requestGPUType to modelSpec

docs/source/conf.py, docs/source/dev_guide/dev_api/engine-stats.rst, docs/source/dev_guide/dev_api/index.rst, docs/source/dev_guide/dev_api/request-stats.rst, docs/source/dev_guide/dev_api/router-logic.rst, docs/source/dev_guide/dev_api/service-discovery.rst
* Add dev API docs
* Fix sphinx bugs
---
<details>
<ul> …
=> [Doc] dev api docs, bug fixes

helm/templates/_helpers.tpl, helm/values.schema.json, helm/values.yaml, tutorials/01-minimal-helm-installation.md
Adding explicit resource limit values to allow limits to be skipped entirely, or set higher than the minimum requests
Adds limitCPU and limitMemory values. 
No longer sets limit equal to the requestCPU and requestMemory values
FIX #254
---
<details>
<ul> …
=> [Feat] add explicit resource limit values

tutorials/08-benchmark-multi-round-qa-multi-gpu.md
Fixes some typos in tutorial. 
---
<details>
<ul> …
=> [Doc] Minor fix in tutorial

benchmarks/multi-round-qa/plot.py, benchmarks/multi-round-qa/run.sh
Minor fix in benchmarking script. 
---
<details>
<ul> …
=> [Doc] Minor fix in benchmarking scripts

helm/templates/deployment-vllm-multi.yaml, helm/values.schema.json, helm/values.yaml
We use different `schedulerName` for GPU resources.
It would be great if user could configure their `schedulerName` in `servingEngineSpec`.
---
<details>
<ul> …
=> [Misc] Add `schedulerName` in servingEngineSpec

benchmarks/multi-round-qa/plot.py, benchmarks/multi-round-qa/run.sh, tutorials/00-install-kubernetes-env.md, tutorials/08-benchmark-multi-round-qa-multi-gpu.md
Minor fixes in benchmark script
---
<details>
<ul> …
=> [Benchmark] Minor fix in benchmark script

tutorials/07-benchmark-multi-round-qa-single-gpu.md, tutorials/08-benchmark-multi-round-qa-multi-gpu.md
Fixes minor typos in tutorials.
---
<details>
<ul> …
=> [Doc] Minor fix in tutorials

helm/templates/deployment-vllm-multi.yaml, helm/values.yaml
This allows more flexibility for adding additional storage. Particularly useful for adding tmp dirs for clusters enforcing read only file systems
FIX #279
---
<details>
<ul> …
=> [Feat] add extraVolume and extraVolumeMount helm variables

helm/templates/deployment-vllm-multi.yaml, helm/values.schema.json, helm/values.yaml
Add support for defining pod and container level securityContext for all serving engines.
For clusters enforcing Pod Security Admission, being able to override the default securtiy context value is a must and it is good practice in order to increase security of the deployment
FIX #281 
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the type of change. Please use …
=> [Feat] add security context to servingEngineSpec

README.md
* Documentation link
---
<details>
<ul>
<li><code>[Feat]</code> for new …
=> [Doc] add docs link to readme

.github/workflows/deploy-docs.yml, docs/source/dev_guide/dev_api/engine-stats.rst, docs/source/getting_started/troubleshooting.rst, docs/source/tutorials/disagg.rst
* Github action for deploying documentation website
<details>
<ul> …
=> [CI/Build] Github action for building docs pipeline

docs/source/getting_started/examples.rst, docs/source/tutorials/kv_cache.rst, tutorials/04-launch-multiple-model.md, tutorials/05-offload-kv-cache.md
FIX https://github.com/vllm-project/production-stack/issues/303
---
<details>
<ul> …
=> [Bugfix]: add missing v1 prefix

README.md
Fix a dead doc link in readme
---
<details>
<ul> …
=> [Doc] Fix doc link in readme

README.md
---
<details>
<ul>
<li><code>[Doc]</code> for …
=> [Doc] Updating README to include community meeting invite

.github/port-forward.sh, .github/workflows/functionality-helm-chart.yml
Previously when PR #256 is merged, the self-hosted runner didn't reinstall minikube so we still need `sudo` in the CI workflows. Now the runner is rebooted. Therefore, we need to remove `sudo` in `minikube` and `kubectl` commands. 
---
<details>
<ul> …
=> [CI/Build] Remove sudo requirements in CI/CD

.github/workflows/router-e2e-test.yml
Add coverage tracking and disable semantic_cache in Docker build for test image.
[coverage.txt](https://github.com/user-attachments/files/19493817/coverage.txt)
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the type of …
=> [CI] Add coverage tracking

.github/workflows/functionality-helm-chart.yml
While debugging failed Helm functionality CI tests in #264 we would've been grateful to have the logs of the failed Helm functionality checks as well as the succeeded ones. This change adds a `if: always()` clause to all log upload steps in the `Functionality test for helm chart` workflow so they can be downloaded even if the actual check failed.
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is …
=> [CI] Always upload logs of Helm functionality checks

.github/workflows/router-e2e-test.yml
Remove Minikube setup, Docker image build/load, and unused chmod/REPO lines from E2E workflow.
---
<details>
<ul>
<li><code>[Bugfix]</code> for bug …
=> [CI] Remove Minikube and Docker-related steps

src/vllm_router/dynamic_config.py, src/vllm_router/routers/metrics_router.py, src/vllm_router/routers/routing_logic.py, src/vllm_router/service_discovery.py, src/vllm_router/services/request_service/request.py, src/vllm_router/services/request_service/rewriter.py
This PR adds copyright notice headers. 
---
<details>
<ul> …
=> [Misc] Adding copyright notice header

src/vllm_router/dynamic_config.py, src/vllm_router/routers/metrics_router.py, src/vllm_router/routers/routing_logic.py, src/vllm_router/service_discovery.py, src/vllm_router/services/request_service/request.py, src/vllm_router/services/request_service/rewriter.py
---
<details>
<ul>
<li><code>[Doc]</code> for …
=> [Misc] Minor fix in copyright headers

tutorials/00-install-kubernetes-env.md, tutorials/01-minimal-helm-installation.md, tutorials/02-basic-vllm-config.md, tutorials/03-load-model-from-pv.md, tutorials/04-launch-multiple-model.md, tutorials/05-offload-kv-cache.md, tutorials/06-remote-shared-kv-cache.md, tutorials/07-benchmark-multi-round-qa-single-gpu.md, tutorials/08-benchmark-multi-round-qa-multi-gpu.md, tutorials/09-lora-enabled-installation.md, tutorials/11-secure-vllm-serve.md, tutorials/12-distributed-tracing.md, tutorials/assets/values-01-minimal-example.yaml
Fix tutorial hyper link
---
<h3>[Doc Improvement]Fix tutorial hyper link</h3>
<p>Fixed the tutorial hyper links in the tutorials section</p>
=> [Doc Improvement]Fix tutorial hyper link

benchmarks/multi-round-qa/README.md, benchmarks/multi-round-qa/multi-round-qa.py
- This PR add `api-key` option at `multi-round-qa.py` script runtime arguments.
- Some api server need api-key(Bearer token) but benchmark script does not have this option.
- Update `README.md` too along updated usage.
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the type …
=> [Benchmark] Add api key option

observability/README.md
Fix the tutorial issue about the crd APIs invalid path.
FIX #358  (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Documentation] fix document issue

src/vllm_router/stats/log_stats.py, src/vllm_router/stats/request_stats.py
FIX #361  (*link existing issues this PR will resolve*)
```
==================================================                                                                                             
Model: distilgpt2                                                                                                                              
Server: http://10.244.110.63:8000                                                                                                              
Engine Stats: Running Requests: 0.0, Queued Requests: 0.0, GPU Cache Hit Rate: 0.00                                                           
Request Stats: QPS: 4.80, Avg Latency: 0.05, Avg ITL: -1, Prefill Requests: 0, Decoding Requests: 0, Swapped Requests: 0, Finished: …
```
=> [Feat] Enabled latency monitor and added average latency computation logic

src/router-controller/api/v1alpha1/staticroute_types.go, src/router-controller/config/crd/bases/production-stack.vllm.ai_staticroutes.yaml, src/router-controller/config/manager/kustomization.yaml, src/router-controller/config/manager/manager.yaml
FIX #365  (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Bugfix] Deprecated least loaded routing logic

helm/templates/service-router.yaml, helm/values.yaml
Add Helm parameter to specify the service type of the router service.
---
<details>
<ul> …
=> [Feat] helm: add routerSpec.serviceType value

deployment_on_cloud/gcp/entry_point_basic.sh
- The version used by the tutorial is not supported. Got this error:
```
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Master version "1.31.5-gke.1023000" is unsupported.
```
Fixed it with version `1.32.3-gke.1440000`
- The syntax of scopes are not correct, Got this error:
```
ERROR: (gcloud.beta.container.clusters.create) unrecognized arguments:
https://www.googleapis.com/auth/logging.write,
https://www.googleapis.com/auth/monitoring,
https://www.googleapis.com/auth/servicecontrol,
https://www.googleapis.com/auth/service.management.readonly,
https://www.googleapis.com/auth/trace.append
```
Fixed
**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE …
=> [Doc] Fix issues in deployment_on_cloud for GCP

deployment_on_cloud/gcp/OPT125_CPU/README.md, deployment_on_cloud/gcp/README.md
`eksctl` is specific to AWS, not GCP.
<details>
<ul>
<li><code>[Feat]</code> …
=> [Docs] Remove eksctl from gcp readme

helm/templates/deployment-vllm-multi.yaml, helm/templates/service-vllm.yaml
This PR fixes the following issue https://github.com/vllm-project/production-stack/issues/375
Expected behavior:  each engine should be associated with a unique service instance when using two helm releases with the same model and in the same namespace.
```
$ helm list
NAME      	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART           	APP VERSION
vllm-test1	default  	1       	2025-04-22 16:09:11.813532 -0400 EDT	deployed	vllm-stack-0.1.1	           
vllm-test2	default  	1       	2025-04-22 16:11:35.238222 -0400 EDT	deployed	vllm-stack-0.1.1	           
$ kubectl get svc
NAME                                TYPE           CLUSTER-IP       EXTERNAL-IP                            PORT(S)             AGE
vllm-test1-opt125m-engine-service   ClusterIP      172.21.53.45 …
```
=> [Bugfix] Fixing issues on the engine svc labels

helm/templates/deployment-vllm-multi.yaml, helm/values.yaml, tutorials/assets/values-01-2pods-minimal-example.yaml, tutorials/assets/values-04-multiple-models.yaml
This PR enhances the serving engine configuration by introducing support for the following vllmConfig parameters:
- `maxNumSeqs:` Maximum number of sequences processed per iteration.
- `maxLoras`: Maximum number of LoRA models loaded simultaneously.
- `gpuMemoryUtilization`: Fraction of GPU memory allocated for model execution.
---
<details>
<h3>PR …
=> [Feat] Support Multi-Model Deployment with Enhanced vLLM Configurations

benchmarks/multi-round-qa/prepare_sharegpt_data.sh
Adding missing ``prepare_sharegpt.sh`` file.
Closes #347 
---
<details>
<ul> …
=> [Bugfix] add prepare sharegpt script

src/vllm_router/protocols.py
FIX #380 (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Bugfix] Declare logger properly for protocols.py

helm/templates/deployment-vllm-multi.yaml, tutorials/assets/values-06-shared-storage.yaml
Fixing the docker image for remote KV cache sharing 
FIX #378 (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Misc] Updating default LMCache docker image for remote KV cache sharing

benchmarks/multi-round-qa/data_preprocessing.py
Closes #385 
---
<details>
<ul>
<li><code>[Feat]</code> for new features in …
=> [Bugfix] Add missing preprocessing file for sharegpt benchmark

helm/Chart.yaml, helm/templates/deployment-vllm-multi.yaml, tutorials/14-vllm-v1.md, tutorials/assets/values-06-shared-storage.yaml, tutorials/assets/values-14-vllm-v1.yaml
This PR adds a tutorial (and changing corresponding helm chart values) for using vLLM v1 in production stack. 
---
<details>
<ul> …
=> [Feat] Adding a tutorial for using vLLM v1 in production stack

docs/source/user_manual/kv_cache/index.rst
=> docs(kv_cache): fix typo

helm/values.yaml
=> [FEAT]: add extraVolumes and extraVolumeMounts options

src/vllm_router/services/request_service/request.py
We've noticed in deployment that the call_request callback background-job wasn't being run because the logic was accidentally placed within the `if request.app.state.semantic_cache_available:`.
As the callback has no functional dependency on the semantic-cache, we should change this so that the callback will be called correctly.
---
<details>
<p>Please try to classify …
=> [Bugfix][Router] make post_request callback not dependent on semantic-cache

helm/templates/deployment-vllm-multi.yaml, helm/values.schema.json, helm/values.yaml
This PR adds support for manual scheduling of an engine pod. It supports the use-cases where an application needs to bypass the Kubernetes scheduler and directly assign a pod to a target node. 
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the type of change. Please use one …
=> Support for Manual Scheduling of an Engine Pod

src/vllm_router/parsers/parser.py
=> [Misc] add miss argument type set

tutorials/00-install-kubernetes-env.md
FIX #404 (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Doc] Added documentation about uninstalling previous minikube installation

src/router-controller/cmd/main.go, src/router-controller/go.mod, src/router-controller/internal/controller/staticroute_controller.go
=> [Feat] feature: add event when Reconciling configmap failed

docs/source/dev_guide/dev_api/router-logic.rst, src/vllm_router/routers/routing_logic.py
Small doc addition for API based on kv aware routing #403  
---
<details>
<ul> …
=> [Doc] doc update for kv aware routing

helm/templates/deployment-vllm-multi.yaml
Fixes the helm chart for vLLM v1. 
FIX #407 (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Misc] Update helm chart template for vLLM v1 

src/tests/test_parser.py, src/vllm_router/app.py, src/vllm_router/parsers/parser.py
This seems like an in-between solution to not touch too many files. Regarding the longterm, I'm not too sure, if we shouldn't switch to a parser that allows configfiles by default. E.g. click with plugins
This just makes it work at all and adds tests for the functionality.
FIX #408
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the type of change. Please use one …
=> [Bugfix][Router]: fix dynamic config not working

src/vllm_router/run-router.sh
Change default behavior of the `run-router.sh` script so that new contributors don't have to configure their environment before testing their changes
FIX https://github.com/vllm-project/production-stack/issues/418
---
<details>
<ul>
<li><code>[Bugfix]</code> for bug …
=> [Bugfix][Router] fix(vllm-router): use roundrobin in run-router.sh

pyproject.toml
This PR updates LMCache version in pyproject.toml
---
<details>
<ul> …
=> [Misc] Update LMCache version in pyproject.toml

README.md, docs/requirements-docs.txt, src/tests/test_utils.py, src/vllm_router/README.md, src/vllm_router/app.py, src/vllm_router/dynamic_config.py, src/vllm_router/parsers/parser.py, src/vllm_router/service_discovery.py, src/vllm_router/services/request_service/request.py, src/vllm_router/utils.py
This feature allows:
* to preserve compatibility of model names when newer models are released
* allow users to specify known commercial models and route the requests to open weight models instead
E.g. if I want to replace `mistral-7b-instruct` with the more powerful `mistral-nemo-instruct-2407` and not disrupt the users, and at the same time route `gpt-4` to `mistral-nemo-instruct-2407` I could just specify it like this
```sh
python3 -m vllm_router.app \
--static-aliases "mistral-7b-instruct:mistral-nemo-instruct-2407,gpt-4:mistral-nemo-instruct-2407"
```
FIX https://github.com/vllm-project/production-stack/issues/389
---
<details>
<p>Thank you for your contribution to production-stack! Before submitting the pull request, …
=> [Feat][Router] add model aliases

src/vllm_router/app.py
This was an oversight from my side.
Longterm we need better tests in the project
---
<details>
<ul> …
=> [Bugfix][Router] fix router crashing when aliases not specified

helm/values.schema.json
The current version uses a dynamic version that redirects to the latest version and may change over time. It also breaks CUE logic when dealing with the existing configuration.
Two issues provide more details and explain the necessity of the changes.
- https://github.com/cue-lang/cue/issues/3461
- https://github.com/argoproj/argo-workflows/pull/14092
=> [Misc] use schema https://json-schema.org/draft/2020-12/schema

src/router-controller/internal/controller/staticroute_controller.go
FIX None
---
- Removed the unnecessary use of ServiceList and now directly operates on a single service.
<details>
<ul>
<li><code>[Bugfix]</code> for bug …
=> [Router] refactor: Replace services list with a single service object

src/tests/test_utils.py, src/vllm_router/app.py, src/vllm_router/dynamic_config.py, src/vllm_router/parsers/parser.py, src/vllm_router/run-router.sh, src/vllm_router/service_discovery.py, src/vllm_router/utils.py
This has no use right now, but will be used by
https://github.com/vllm-project/production-stack/pull/428 as we need to specify the model types so that the health check can try the correct model with the corresponding data payload.
---
<details>
<ul>
<li><code>[Bugfix]</code> …
=> [Feat][Router] add static-model-types argument

.github/workflows/operator-test.yml, tests/e2e/test-crds.sh
This PR adds an end-to-end testing workflow for validating operator CRDs and CRs. The workflow ensures that our Custom Resource Definitions and Custom Resources are properly formatted and can be created in a Kubernetes cluster.
- Added new workflow file `.github/workflows/operator-test.yml` for operator-specific testing
- Created e2e test script `tests/e2e/test-crds.sh` that:
- Applies and validates CRDs from `operator/config/crd/bases`
- Applies and validates sample CRs from `operator/config/samples`
- Includes proper cleanup of test resources
- Workflow runs on:
- Changes to operator-related files
- Changes to e2e test files
- Changes to the workflow file itself
The workflow has been tested locally with minikube and verifies:
- CRD creation and validation
- CR creation and validation
- …
=> [CI/CD] Adding CI/CD tests for CRDs

.github/workflows/functionality-helm-chart.yml
Avoid wrong context switched in other PRs.
---
<details>
<ul> …
=> [CI/Build] Switch context in CI

pyproject.toml, uv.lock
=> [CI] chore: add unittest coverage

pyproject.toml, uv.lock
This reverts commit 38c5546e7c1b192dec5953185b918fdd1aa525ae since it causes a bug in the CI/CD testing pipeline. 
---
<details>
<ul> …
=> [Misc] Reverting PR #449

tutorials/16-disagg-prefill.md, tutorials/assets/values-16-disagg-prefill.yaml
This PR adds the tutorial for disaggregated prefill. 
---
<details>
<ul> …
=> [Doc] Adding tutorial for Disaggregated Prefill

community/community-event.md, community/prod_stack_community_meeting.ics
---
<details>
<ul>
<li><code>[Doc]</code> for …
=> [Doc] Update community meeting calendar invite 

src/tests/test_parser.py, src/tests/test_static_service_discovery.py, src/tests/test_utils.py, src/vllm_router/README.md, src/vllm_router/app.py, src/vllm_router/parsers/parser.py, src/vllm_router/service_discovery.py, src/vllm_router/utils.py, uv.lock
Requires https://github.com/vllm-project/production-stack/pull/430
Adds health checks to the backends to make sure that they are reachable and disables routing if they are not
FIX https://github.com/vllm-project/production-stack/issues/420
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately …
=> [Feat][Router]: add endpoint health checks to static router

src/vllm_router/services/request_service/request.py
Broke in https://github.com/vllm-project/production-stack/commit/48312e7779bc4c4df6303ec3d7850b0b3cf69767#diff-3e852cfcf107dfd78ee2b7c7e88e05428b7f2bffcfc5ca1dce0c070caf563f2aR139
Same as https://github.com/vllm-project/production-stack/pull/399
We've noticed in deployment that the call_request callback background-job wasn't being run because the logic was accidentally placed within the if request.app.state.semantic_cache_available:.
As the callback has no functional dependency on the semantic-cache, we should change this so that the callback will be called correctly.
---
<details>
<p>Thank you for your contribution to production-stack! …
=> [Bugfix][Request]: make callbacks not require semantic_cache

helm/Chart.yaml
FIX #467 (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Bugfix] Helm chart version update to sync with current changes

observability/README.md, observability/install.sh, observability/kube-prom-stack.yaml
- fix observability/kube-prom-stack.yaml  ServiceMonitors only monitor namespace `default`
- optimization helm install to helm upgrade (It can be upgraded and installed repeatedly)
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR …
=> [Doc] Only the default namespace service monitor namespace

examples/kv_routing/lmcache1.yaml, examples/kv_routing/prod-stack.yaml, helm/templates/deployment-router.yaml, helm/templates/deployment-vllm-multi.yaml, helm/templates/service-router.yaml, src/vllm_router/routers/routing_logic.py
This PR makes KV cache aware routing compatible with the latest LMCache (changes have been made in the KV cache manager API).
---
<details>
<ul>
<li><code>[Bugfix]</code> for bug …
=> [Misc] Making KV aware routing compatible with latest LMCache

src/vllm_router/services/request_service/request.py
FIX #472 
Add functionality to retrieve X-Request-Id from request headers, generating a new uuid as request_id only when X-Request-Id is not present in the request headers. Also ensure all responses include the X-Request-Id header.
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is …
=> [Misc] Update the request_id handling logic to align with vLLM

tutorials/16-disagg-prefill.md
This adds instructions for Kubernetes setup and Helm installation.
---
<details>
<ul> …
=> [Doc] Update disagg prefill tutorial docs

helm/templates/deployment-vllm-multi.yaml
=> [Metrics] Use multi-process prometheus in v1

.github/workflows/scheduled-release.yml
This PR introduces a GitHub Actions workflow to automate the release process for the vLLM production stack, including both Helm chart and router Docker image releases.
- **Dual trigger support**: Scheduled releases (every Monday at 9:00 AM UTC, can be customized later) and manual workflow dispatch
- **Flexible versioning**: Support for patch, minor, and major version bumps with manual override capability
- **Dry run mode**: Test releases without actually publishing
- **Automated release notes**: Generates changelog from merged PRs between releases
- **Version management**: Updates Helm chart version in `Chart.yaml` and creates corresponding Git tags
1. **prepare-release**: Handles version bumping, Git tagging, and release preparation
2. **release-helm**: Publishes Helm charts using …
=> [CI/Build] Add release bot workflow

README.md
This PR adds GMI Cloud as the sponsor in the README page. Special thanks to Yujing from GMI to support our development and benchmarking efforts along the way.
---
<details>
<ul> …
=> [Doc] Add sponsorship section in README

helm/templates/deployment-vllm-multi.yaml
Tiny PR to change the entrypoint for the new nightly lmcache/vllm-openai docker images!
=> [CI]: change the entrypoint of nightly docker images

helm/templates/role.yaml, src/vllm_router/routers/main_router.py, src/vllm_router/service_discovery.py, src/vllm_router/services/request_service/request.py, tutorials/19-engine-sleep-wakeup-mode.md, tutorials/assets/values-19-sleep-mode-aware.yaml
This PR extends the router to support the `/sleep`, `/wake_up` and `/is_sleeping` endpoints, for example:  sending `sleep`, `wake_up` or `is_sleeping` request for a specific vLLM engine;
For a successful `sleep` request, the router adds the label `sleeping: "true"` to the pod so that if there are other routers, they can pick up the change and update their local cache (e.g, set is_sleeping=true) - the router is already doing a k8s watch to discovery new engines and updates. Hence, all the routers will become aware that a specific vLLM instance is sleeping and not ready to handle requests. 
Similarly, for a successful `wake_up` request the router removes the label `sleeping: "true"` from the engine pod so that if there are other routers, they can pick up the change and update their local …
=> Second Level Support for vLLM V1 Sleep & Wake_up Mode (/sleep, /wake_up & /is_sleeping endpoints)

helm/templates/deployment-cache-server.yaml, helm/templates/deployment-vllm-multi.yaml, tutorials/assets/values-06-shared-storage.yaml
add health probe for lmcache server 
FIX #310  (*link existing issues this PR will resolve*)
---
<details>
<ul>
<li><code>[CI/Build]</code> …
=> [Bugfix] add health probe for lmcache server 

docs/source/tutorials/disagg.rst, tutorials/assets/values-16-disagg-prefill.yaml
This PR adds security context for disaggregated prefill as requested by NIXL. 
---
<details>
<ul> …
=> [Doc] Adding security context for disaggregated prefill 

src/vllm_router/routers/routing_logic.py, src/vllm_router/service_discovery.py, src/vllm_router/services/request_service/request.py
This removes unused variables to pass ruff checks. 
FIX #553 (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Minor] Removing unused variables to pass ruff checks

src/vllm_router/services/request_service/request.py
=> [Minor] Missing variable found by ruff 

src/gateway_inference_extension/Dockerfile
FIX #571 (*link existing issues this PR will resolve*)
---
<details>
<ul> …
=> [Minor] Adding commit number in GIE support's Dockerfile

README.md
=> [Doc] Updating community meeting time on README

README.md
Minor fix to update the community meeting slots. 
---
<details>
<ul> …
=> [Doc] Minor fix in README 

src/vllm_router/prefix/hashtrie.py
Acquire lock when updating `endpoints` in trie insertion to prevent race conditions when `insert()` and `longest_prefix_match()` are called concurrently.
#59
---
<details>
<ul> …
=> [Bugfix] Acquire lock when updating `endpoints` in trie insertion

helm/Chart.yaml
Bumping version to 0.1.6. 
---
<details>
<ul> …
=> Bumping version to 0.1.6

requirements-test.txt
=> Transformers

requirements-test.txt
=> [CI/Build] Specify transformers version in router end to end test

src/vllm_router/utils.py
Some models see the max_completion_tokens as extra input and return error messages e.g. {'detail': [{'type': 'extra_forbidden', 'loc': ['body', 'max_completion_tokens'], 'msg': 'Extra inputs are not permitted', 'input': 3}]}
---
<details>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the …
=> [Bugfix][Router]: simplify test payload

utils/install-minikube-cluster.sh
This PR replaces `--memory=max` with a computed value from a new helper function - `calculate_safe_memory` - and passes it to minikube start via `MINIKUBE_MEM`. The goal is to avoid starving the host when running Minikube on laptops/desktops with limited RAM.
---
<details>
<p>Please …
=> [Misc] Auto-size Minikube memory via calculate_safe_memory

docs/source/index.rst
As title, add a missing word "metrics" in the feature description.
=> [Doc] Add a missing word in the description

docs/source/use_cases/kv-cache-aware-routing.rst
This pull request updates the documentation for KV cache aware routing in the vLLM Production Stack. The modifications clarify the routing mechanism, emphasizing that requests are routed to instances with the highest KV cache hit rate, rather than solely based on shared prefixes, to optimize performance and cache utilization.
---
<details>
<p>Please try to classify PRs …
=> [Docs] Modify the kvaware routing doc

observability/prom-adapter.yaml, src/vllm_router/service_discovery.py, src/vllm_router/services/metrics_service/__init__.py, src/vllm_router/services/request_service/request.py, tutorials/20-keda-autoscaling.md, tutorials/assets/values-20-keda.yaml
This PR introduces functionality that enables KEDA to scale workloads down to zero replicas when there is no demand. To support this capability, several supporting features are added:
1. New metric for incoming requests – Tracks all incoming requests, including those rejected when no backend is available. This metric is required as a scale-up trigger.
2. Model registry – Maintains a registry of all known models, allowing the router to distinguish between hibernated models and unknown models.
---
<details>
<p>Thank you for your contribution to production-stack! Before submitting the pull request, please ensure the PR meets the following …
=> [Feat] Add support for scaling down to zero in KEDA

.github/workflows/router-e2e-test.yml, pyproject.toml, requirements-test.txt
---
<details>
<ul>
<li><code>[Doc]</code> for …
=> [CI] move e2e machine to self hosted

src/vllm_router/app.py, src/vllm_router/service_discovery.py
Fix pd client initialization issue.
Currently the pd clients are initialized when router starts, however, engines normally will not be ready this time. As a result the pd client will never get initialized.
This fix will try initialized the pd clients every time an engine is discovered. 
---
<details>
<p>Please try to classify PRs for easy understanding of the type of …
=> [Bugfix] fix pd client initialization issue
